# Generated by Django 5.1.3 on 2025-06-15 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_coachingrequest_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagecontent',
            name='journey_subtitle',
            field=models.CharField(default='نحو تطوير الذات واكتشاف القدرات الكامنه', max_length=255, verbose_name='Journey Subtitle'),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='journey_title',
            field=models.CharField(default='رحلتى', max_length=255, verbose_name='Journey Title'),
        ),
    ]
